version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run: sudo apt update && sudo apt install software-properties-common python-software-properties
      - run:
          name: Get Toolchain ppa
          command: apt-add-repository ppa:wpilib/toolchain -y && apt update
      - run:
          name: Get Toolchain
          command: apt install frc-toolchain -y
      - run:
          name: Build
          command: ./gradlew assemble
